"""
╔══════════════════════════════════════════════════════════════╗
║  main.py  —  Pipeline Orchestrator                          ║
║                                                              ║
║  This file wires the three agents together into a graph     ║
║  and runs the full pipeline.                                 ║
║                                                              ║
║  ⚠️  DO NOT EDIT THIS FILE.                                  ║
║  Your group's bug is in agents/ — fix it there.             ║
╚══════════════════════════════════════════════════════════════╝

HOW TO RUN:
  python main.py
"""

from langgraph.graph import StateGraph, END
from config.settings import DigestState
from agents.fetcher import fetcher_node
from agents.tagger import tagger_node
from agents.editor import editor_node

# ─── BUILD THE GRAPH ─────────────────────────────────────────────────────────
workflow = StateGraph(DigestState)

workflow.add_node("fetcher", fetcher_node)
workflow.add_node("tagger",  tagger_node)
workflow.add_node("editor",  editor_node)

workflow.set_entry_point("fetcher")
workflow.add_edge("fetcher", "tagger")
workflow.add_edge("tagger",  "editor")
workflow.add_edge("editor",  END)

app = workflow.compile()

# ─── RUN ─────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    inputs = {
        "topic":    "Scientists discover a new deep-sea creature near volcanic vents",
        "summary":  "",
        "tags":     "",
        "headline": ""
    }

    print("🚀 Starting News Digest Pipeline...\n")

    accumulated = {**inputs}
    for step in app.stream(inputs):
        for node_output in step.values():
            accumulated.update(node_output)

    print("\n" + "═" * 55)
    print("📰  FINAL DIGEST")
    print("═" * 55)
    print(f"📋  Summary  : {accumulated.get('summary',  '[missing]')}")
    print(f"🏷️   Tags     : {accumulated.get('tags',     '[missing]')}")
    print(f"📰  Headline : {accumulated.get('headline', '[missing]')}")
    print("═" * 55)
